import 'package:get/get.dart';

import '../app/data/constants/string_constants.dart';

class LanguageTranslate extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'en_US': {
          StringConstants.chooseTheLanguageFamiliarToYou: StringConstants
              .chooseTheLanguageFamiliarToYou,
          StringConstants.english: StringConstants.english,
          StringConstants.rot: StringConstants.rot,
          StringConstants.spanish: StringConstants.spanish,
          StringConstants.login: StringConstants.login,
          StringConstants.returnMade: StringConstants.returnMade,
          StringConstants.orderDetails: StringConstants.orderDetails,
          StringConstants.loginWithGoogle: StringConstants.loginWithGoogle,
          StringConstants.loginWithFacebook: StringConstants.loginWithFacebook,
          StringConstants.loginWithEmail: StringConstants.loginWithEmail,
          StringConstants.loginWithPhone: StringConstants.loginWithPhone,
          StringConstants.signUpWithPhone: StringConstants.signUpWithPhone,
          StringConstants.signUpWithEmail: StringConstants.signUpWithEmail,
          StringConstants.doNotHaveAnAccount: StringConstants
              .doNotHaveAnAccount,
          StringConstants.enterYourPhoneNumber: StringConstants
              .enterYourPhoneNumber,
          StringConstants.enterYourFullName: StringConstants.enterYourFullName,
          StringConstants.enterYourEmail: StringConstants.enterYourEmail,
          StringConstants.enterYourGender: StringConstants.enterYourGender,
          StringConstants.gender: StringConstants.gender,
          StringConstants.enterYourDob: StringConstants.enterYourDob,
          StringConstants.enterYourEmailAndPassword: StringConstants
              .enterYourEmailAndPassword,
          StringConstants.pleaseEnterPassword: StringConstants
              .pleaseEnterPassword,
          StringConstants.enterYourFirstName: StringConstants
              .enterYourFirstName,
          StringConstants.enterYourLastName: StringConstants.enterYourLastName,
          StringConstants.enterYourSellersAddress: StringConstants
              .enterYourSellersAddress,
          StringConstants.firstName: StringConstants.firstName,
          StringConstants.lastName: StringConstants.lastName,
          StringConstants.dob: StringConstants.dob,
          StringConstants.sellersAddress: StringConstants.sellersAddress,
          StringConstants.resetPassword: StringConstants.resetPassword,
          StringConstants.checkYourSms: StringConstants.checkYourSms,
          StringConstants.checkYourMail: StringConstants.checkYourMail,
          StringConstants
              .pleasePutYourMobileNumberToResetYourPassword: StringConstants
              .pleasePutYourMobileNumberToResetYourPassword,
          StringConstants.pleasePutYourEmailToResetYourPassword: StringConstants
              .pleasePutYourEmailToResetYourPassword,
          StringConstants.profile: StringConstants.profile,
          StringConstants.publicInformation: StringConstants.publicInformation,
          StringConstants.personalInformation: StringConstants
              .personalInformation,
          StringConstants.reviews: StringConstants.reviews,
          StringConstants.account: StringConstants.account,
          StringConstants.home: StringConstants.home,
          StringConstants.favorites: StringConstants.favorites,
          StringConstants.chats: StringConstants.chats,
          StringConstants.sales: StringConstants.sales,
          StringConstants.purchases: StringConstants.purchases,
          StringConstants.wallet: StringConstants.wallet,
          StringConstants.subscription: StringConstants.subscription,
          StringConstants.generalSetting: StringConstants.generalSetting,
          StringConstants.changePassword: StringConstants.changePassword,
          StringConstants.help: StringConstants.help,
          StringConstants.myQRCode: StringConstants.myQRCode,
          StringConstants.user: StringConstants.user,
          StringConstants.following: StringConstants.following,
          StringConstants.logOut: StringConstants.logOut,
          StringConstants.signUp: StringConstants.signUp,
          StringConstants.password: StringConstants.password,
          StringConstants.fullName: StringConstants.fullName,
          StringConstants.email: StringConstants.email,
          StringConstants.assignedRole: StringConstants.assignedRole,
          StringConstants.phoneNumber: StringConstants.phoneNumber,
          StringConstants.passwordReset: StringConstants.passwordReset,
          StringConstants.or: StringConstants.or,
          StringConstants.next: StringConstants.next,
          StringConstants.profilePublic: StringConstants.profilePublic,
          StringConstants.pleasePutTheSixDigitsSentToYou: StringConstants
              .pleasePutTheSixDigitsSentToYou,
          StringConstants.createNewPassword: StringConstants.createNewPassword,
          StringConstants
              .yourNewPasswordMustBeDifferentFromPreviousUsedPasswords: StringConstants
              .yourNewPasswordMustBeDifferentFromPreviousUsedPasswords,
          StringConstants.pleaseEnterNewPassword: StringConstants
              .pleaseEnterNewPassword,
          StringConstants.pleaseEnterConfirmPassword: StringConstants
              .pleaseEnterConfirmPassword,
          StringConstants.currentPassword: StringConstants.currentPassword,
          StringConstants.newPassword: StringConstants.newPassword,
          StringConstants.confirmPassword: StringConstants.confirmPassword,
          StringConstants.save: StringConstants.save,
          StringConstants.myProfile: StringConstants.myProfile,
          StringConstants.rateUs: StringConstants.rateUs,
          StringConstants.welcome: StringConstants.welcome,
          StringConstants.message: StringConstants.message,
          StringConstants.total: StringConstants.total,
          StringConstants.productsStatus: StringConstants.productsStatus,
          StringConstants.notification: StringConstants.notification,
          StringConstants.upload: StringConstants.upload,
          StringConstants.submit: StringConstants.submit,
          StringConstants.placeAnAdHere: StringConstants.placeAnAdHere,
          StringConstants.search: StringConstants.search,
          StringConstants.cart: StringConstants.cart,
          StringConstants.welcomeToFertileMate: StringConstants
              .welcomeToFertileMate,
          StringConstants.aIDrivenFertilityAnalysis: StringConstants
              .aIDrivenFertilityAnalysis,
          StringConstants.comprehensiveHealthAssessments: StringConstants
              .comprehensiveHealthAssessments,
          StringConstants.boostYourFertilityToday: StringConstants
              .boostYourFertilityToday,
          StringConstants.getStarted: StringConstants.getStarted,
          StringConstants.yourReproductiveHealthJourney: StringConstants
              .yourReproductiveHealthJourney,
          StringConstants.support: StringConstants.support,
          StringConstants.supportText: StringConstants.supportText,
          StringConstants.availableNow: StringConstants.availableNow,
          StringConstants.chatNow: StringConstants.chatNow,
          StringConstants.chat: StringConstants.chat,
          StringConstants.healthAssessment: StringConstants.healthAssessment,
          StringConstants.bloodTests: StringConstants.bloodTests,
          StringConstants.result: StringConstants.result,
          StringConstants.prediabetesAssessment: StringConstants
              .prediabetesAssessment,
          StringConstants.document: StringConstants.document,
          StringConstants.personalInfo: StringConstants.personalInfo,
          StringConstants.yourName: StringConstants.yourName,
          StringConstants.occupation: StringConstants.occupation,
          StringConstants.employer: StringConstants.employer,
          StringConstants.usCitizen: StringConstants.usCitizen,
          StringConstants.contactInfo: StringConstants.contactInfo,
          StringConstants.rotProtection: StringConstants.rotProtection,
          StringConstants.buyWithoutWorries: StringConstants.buyWithoutWorries,
          StringConstants.edit: StringConstants.edit,
          StringConstants.shareYourOpinion: StringConstants.shareYourOpinion,
          StringConstants.yourRatingForThisProductGood: StringConstants
              .yourRatingForThisProductGood,
          StringConstants.typeHere: StringConstants.typeHere,
          StringConstants.send: StringConstants.send,
          StringConstants.categories: StringConstants.categories,
          StringConstants.seeAll: StringConstants.seeAll,
          StringConstants.reportProduct: StringConstants.reportProduct,
          StringConstants.electronics: StringConstants.electronics,
          StringConstants.nearYou: StringConstants.nearYou,
          StringConstants.bestSeller: StringConstants.bestSeller,
          StringConstants.share: StringConstants.share,
          StringConstants.rotAllRightsReserved: StringConstants
              .rotAllRightsReserved,
          StringConstants.changeOfConsent: StringConstants.changeOfConsent,
          StringConstants.privacyPolicies: StringConstants.privacyPolicies,
          StringConstants.termsAndConditions: StringConstants
              .termsAndConditions,
          StringConstants.legalWarning: StringConstants.legalWarning,
          StringConstants.legal: StringConstants.legal,
          StringConstants.coexistenceRules: StringConstants.coexistenceRules,
          StringConstants.securityAdvice: StringConstants.securityAdvice,
          StringConstants.tipsAndRules: StringConstants.tipsAndRules,
          StringConstants.consultationInProgress: StringConstants
              .consultationInProgress,
          StringConstants.helpCenter: StringConstants.helpCenter,
          StringConstants.medium: StringConstants.medium,
          StringConstants.addNewAccount: StringConstants.addNewAccount,
          StringConstants.cars: StringConstants.cars,
          StringConstants.motorcycle: StringConstants.motorcycle,
          StringConstants.realEstate: StringConstants.realEstate,
          StringConstants.employment: StringConstants.employment,
          StringConstants.business: StringConstants.business,
          StringConstants.services: StringConstants.services,
          StringConstants.computer: StringConstants.computer,
          StringConstants.phone: StringConstants.phone,
          StringConstants.baby: StringConstants.baby,
          StringConstants.games: StringConstants.games,
          StringConstants.fashion: StringConstants.fashion,
          StringConstants.sports: StringConstants.sports,
          StringConstants.leisure: StringConstants.leisure,
          StringConstants.agriculture: StringConstants.agriculture,
          StringConstants.community: StringConstants.community,
          StringConstants.training: StringConstants.training,
          StringConstants.imageAndSound: StringConstants.imageAndSound,
          StringConstants.sportsAndNautical: StringConstants.sportsAndNautical,
          StringConstants.computerAndElectronic: StringConstants
              .computerAndElectronic,
          StringConstants.hobbiesAndLeisure: StringConstants.hobbiesAndLeisure,
          StringConstants.engineAndAccessories: StringConstants
              .engineAndAccessories,
          StringConstants.homeAndGarden: StringConstants.homeAndGarden,
          StringConstants.collecting: StringConstants.collecting,
          StringConstants.tourism: StringConstants.tourism,
          StringConstants.description: StringConstants.description,
          StringConstants.title: StringConstants.title,
          StringConstants.category: StringConstants.category,
          StringConstants.productLocation: StringConstants.productLocation,
          StringConstants.city: StringConstants.city,
          StringConstants.country: StringConstants.country,
          StringConstants.zipCode: StringConstants.zipCode,
          StringConstants.brand: StringConstants.brand,
          StringConstants.hashtag: StringConstants.hashtag,
          StringConstants.price: StringConstants.price,
          StringConstants.currency: StringConstants.currency,
          StringConstants.postAdd: StringConstants.postAdd,
          StringConstants.hire: StringConstants.hire,
          StringConstants.rent: StringConstants.rent,
          StringConstants.exchange: StringConstants.exchange,
          StringConstants.buy: StringConstants.buy,
          StringConstants.learnMore: StringConstants.learnMore,
          StringConstants.sell: StringConstants.sell,
          StringConstants.enableShipping: StringConstants.enableShipping,
          StringConstants.keepExploring: StringConstants.keepExploring,
          StringConstants.ongoing: StringConstants.ongoing,
          StringConstants.completed: StringConstants.completed,
          StringConstants.inWind: StringConstants.inWind,
          StringConstants.inProgress: StringConstants.inProgress,
          StringConstants.finished: StringConstants.finished,
          StringConstants.products: StringConstants.products,
          StringConstants.published: StringConstants.published,
          StringConstants.info: StringConstants.info,
          StringConstants.searches: StringConstants.searches,
          StringConstants.friend: StringConstants.friend,
          StringConstants.editPrice: StringConstants.editPrice,
          StringConstants.forSecurity: StringConstants.forSecurity,
          StringConstants.getPaid: StringConstants.getPaid,
          StringConstants.purchasesStatus: StringConstants.purchasesStatus,
          StringConstants.twoStepVerification: StringConstants
              .twoStepVerification,
          StringConstants.useVerificationMethods: StringConstants
              .useVerificationMethods,
          StringConstants.verifyThatThisAccount: StringConstants
              .verifyThatThisAccount,
          StringConstants.chooseHowToReceive: StringConstants
              .chooseHowToReceive,
          StringConstants.appUnlock: StringConstants.appUnlock,
          StringConstants.linkedDevices: StringConstants.linkedDevices,
          StringConstants.collaborator: StringConstants.collaborator,
          StringConstants.unlockingTheApp: StringConstants.unlockingTheApp,
          StringConstants.youUseTouchId: StringConstants.youUseTouchId,
          StringConstants.myProducts: StringConstants.myProducts,
          StringConstants.addNewCard: StringConstants.addNewCard,
          StringConstants.getNotifiedIfAnyOfYourProductsExpire: StringConstants
              .getNotifiedIfAnyOfYourProductsExpire,
          StringConstants.expiredProducts: StringConstants.expiredProducts,
          StringConstants.mySearches: StringConstants.mySearches,
          StringConstants.myFavorites: StringConstants.myFavorites,
          StringConstants.searchAlerts: StringConstants.searchAlerts,
          StringConstants.priceDrop: StringConstants.priceDrop,
          StringConstants.favoritesSold: StringConstants.favoritesSold,
          StringConstants.favoritesReserved: StringConstants.favoritesReserved,
          StringConstants.newProducts: StringConstants.newProducts,
          StringConstants.additionalOptions: StringConstants.additionalOptions,
          StringConstants.tipsTndSuggestions: StringConstants
              .tipsTndSuggestions,
          StringConstants.promotionsAndNewFeatures: StringConstants
              .promotionsAndNewFeatures,
          StringConstants.collaborators: StringConstants.collaborators,
          StringConstants.somethingWentWrong: StringConstants
              .somethingWentWrong,
          StringConstants.weAreWorkingToSolveIt: StringConstants
              .weAreWorkingToSolveIt,
          StringConstants.ifTheProblemPersists: StringConstants
              .ifTheProblemPersists,
          StringConstants.code: StringConstants.code,
          StringConstants.retry: StringConstants.retry,
          StringConstants.useAnotherMethod: StringConstants.useAnotherMethod,
          StringConstants.eliminate: StringConstants.eliminate,
          StringConstants.readyWeSendYour: StringConstants.readyWeSendYour,
          StringConstants.theInvitationIsValidUntilSunday: StringConstants
              .theInvitationIsValidUntilSunday,
          StringConstants.resendInvitation: StringConstants.resendInvitation,
          StringConstants.createAnotherInvitation: StringConstants
              .createAnotherInvitation,
          StringConstants.seeYourCollaborators: StringConstants
              .seeYourCollaborators,
          StringConstants.seeDetails: StringConstants.seeDetails,
          StringConstants.inviteCollaborator: StringConstants
              .inviteCollaborator,
          StringConstants.manageRoles: StringConstants.manageRoles,
          StringConstants.enterTheEmailOfTheCollaborator: StringConstants
              .enterTheEmailOfTheCollaborator,
          StringConstants.keepInMindThatYourEmailMust: StringConstants
              .keepInMindThatYourEmailMust,
          StringConstants.continueText: StringConstants.continueText,
          StringConstants.protectedByReCAPTCHA: StringConstants
              .protectedByReCAPTCHA,
          StringConstants.privacy: StringConstants.privacy,
          StringConstants.chooseARole: StringConstants.chooseARole,
          StringConstants.enterTheVerificationCode: StringConstants
              .enterTheVerificationCode,
          StringConstants.youReceived: StringConstants.youReceived,
          StringConstants.resendCode: StringConstants.resendCode,
          StringConstants.administrator: StringConstants.administrator,
          StringConstants.supervisor: StringConstants.supervisor,
          StringConstants.createNewRole: StringConstants.createNewRole,
          StringConstants.goBack: StringConstants.goBack,
          StringConstants.accounts: StringConstants.accounts,
          StringConstants.recharge: StringConstants.recharge,
          StringConstants.charge: StringConstants.charge,
          StringConstants.sendMoney: StringConstants.sendMoney,
          StringConstants.pay: StringConstants.pay,
          StringConstants.withdraw: StringConstants.withdraw,
          StringConstants.historyOfMovements: StringConstants
              .historyOfMovements,
          StringConstants.bankInformation: StringConstants.bankInformation,
          StringConstants.confirm: StringConstants.confirm,
          StringConstants.editRolePermissions: StringConstants
              .editRolePermissions,
          StringConstants.changeEmail: StringConstants.changeEmail,
          StringConstants.changeRole: StringConstants.changeRole,
          StringConstants.iAcceptThe: StringConstants.iAcceptThe,
          StringConstants.converter: StringConstants.converter,
          StringConstants.forTheUseOfTheCollaboratorsTool: StringConstants
              .forTheUseOfTheCollaboratorsTool,
          StringConstants.cancel: StringConstants.cancel,
          StringConstants.keepInWallet: StringConstants.keepInWallet,
          StringConstants.withdrawBalance: StringConstants.withdrawBalance,
          StringConstants.useTheConverter: StringConstants.useTheConverter,
          StringConstants.conditions: StringConstants.conditions,
          StringConstants.sendInvitation: StringConstants.sendInvitation,
          StringConstants.rotPro: StringConstants.rotPro,
          StringConstants.addNew: StringConstants.addNew,
          StringConstants.departures: StringConstants.departures,
          StringConstants.appetizer: StringConstants.appetizer,
          StringConstants.all: StringConstants.all,
          StringConstants.local: StringConstants.local,
          StringConstants.swift: StringConstants.swift,
          StringConstants.bicSwiftCode: StringConstants.bicSwiftCode,
          StringConstants.bankNameAndAddress: StringConstants
              .bankNameAndAddress,
          StringConstants.recipient: StringConstants.recipient,
          StringConstants.useThisData: StringConstants.useThisData,
          StringConstants.provideThisData: StringConstants.provideThisData,
          StringConstants.ifTheIssuingBank: StringConstants.ifTheIssuingBank,
          StringConstants.ifYourEmployer: StringConstants.ifYourEmployer,
          StringConstants.documents: StringConstants.documents,
          StringConstants.bankStatement: StringConstants.bankStatement,
          StringConstants.accountConfirmation: StringConstants
              .accountConfirmation,
          StringConstants.onlyForInternationalTransfers: StringConstants
              .onlyForInternationalTransfers,
          StringConstants.onlyForLocalTransfers: StringConstants
              .onlyForLocalTransfers,
          StringConstants.currencyAccount: StringConstants.currencyAccount,
          StringConstants.flexibleAccount: StringConstants.flexibleAccount,
          StringConstants.pockets: StringConstants.pockets,
          StringConstants.saveMoneyAndManage: StringConstants
              .saveMoneyAndManage,
          StringConstants.jointAccount: StringConstants.jointAccount,
          StringConstants.anAccountForAllTypes: StringConstants
              .anAccountForAllTypes,
          StringConstants.getUpTo: StringConstants.getUpTo,
          StringConstants.proAccount: StringConstants.proAccount,
          StringConstants.howMuchMoneyDoYouWantToRecharge: StringConstants
              .howMuchMoneyDoYouWantToRecharge,
          StringConstants.rateAccordingToTheAmountOfTheRecharge: StringConstants
              .rateAccordingToTheAmountOfTheRecharge,
          StringConstants.reloadWallet: StringConstants.reloadWallet,
          StringConstants.transferToBank: StringConstants.transferToBank,
          StringConstants.howMuchMoney: StringConstants.howMuchMoney,
          StringConstants.rechargeSummary: StringConstants.rechargeSummary,
          StringConstants.rechargeFee: StringConstants.rechargeFee,
          StringConstants.rechargeCarriedOut: StringConstants
              .rechargeCarriedOut,
          StringConstants.goToWallet: StringConstants.goToWallet,
          StringConstants.theMoneyIsAlready: StringConstants.theMoneyIsAlready,
          StringConstants.aReadyToUse: StringConstants.aReadyToUse,
          StringConstants.credit: StringConstants.credit,
          StringConstants.discoverLoansAndCreditCards: StringConstants
              .discoverLoansAndCreditCards,
          StringConstants.accountGreaterThanEighteen: StringConstants
              .accountGreaterThanEighteen,
          StringConstants.linkedAccount: StringConstants.linkedAccount,
          StringConstants.checkAllYourBankAccountsInOnePlace: StringConstants
              .checkAllYourBankAccountsInOnePlace,
          StringConstants.accountsForChildren: StringConstants
              .accountsForChildren,
          StringConstants.moreThanThirtyCurrencies: StringConstants
              .moreThanThirtyCurrencies,
          StringConstants.itOffersYouSolutions: StringConstants
              .itOffersYouSolutions,
          StringConstants.findTheBestSubscription: StringConstants
              .findTheBestSubscription,
          StringConstants.searchForCollaborator: StringConstants
              .searchForCollaborator,
          StringConstants.getNotifiedWhenNewProductsFit: StringConstants
              .getNotifiedWhenNewProductsFit,
          StringConstants.getNotifiedAboutAnyNewsRegarding: StringConstants
              .getNotifiedAboutAnyNewsRegarding,
          StringConstants.getNotifiedAboutPromotionsAndOther: StringConstants
              .getNotifiedAboutPromotionsAndOther,
          StringConstants.payment: StringConstants.payment,
          StringConstants.cardNumber: StringConstants.cardNumber,
          StringConstants.enterDigitCardNumber: StringConstants
              .enterDigitCardNumber,
          StringConstants.validThru: StringConstants.validThru,
          StringConstants.cvv: StringConstants.cvv,
          StringConstants.month: StringConstants.month,
          StringConstants.year: StringConstants.year,
          StringConstants.ok: StringConstants.ok,
          StringConstants.cardHoldersName: StringConstants.cardHoldersName,
          StringConstants.nameOnCard: StringConstants.nameOnCard,
          StringConstants.payMyFriend: StringConstants.payMyFriend,
          StringConstants.cardPayment: StringConstants.cardPayment,
          StringConstants.available: StringConstants.available,
          StringConstants.youPay: StringConstants.youPay,
          StringConstants.address: StringConstants.address,
          StringConstants.streetNameAndNumber: StringConstants
              .streetNameAndNumber,
          StringConstants.floorAndDoorNumber: StringConstants
              .floorAndDoorNumber,
          StringConstants.nearbyPoints: StringConstants.nearbyPoints,
          StringConstants.inPerson: StringConstants.inPerson,
          StringConstants.meetAndPay: StringConstants.meetAndPay,
          StringConstants.pickUpPoint: StringConstants.pickUpPoint,
          StringConstants.viewPickUpPoint: StringConstants.viewPickUpPoint,
          StringConstants.myAddress: StringConstants.myAddress,
          StringConstants.colour: StringConstants.colour,
          StringConstants.deliveryExpectedIn: StringConstants
              .deliveryExpectedIn,
          StringConstants.purchaseMade: StringConstants.purchaseMade,
          StringConstants.theSellerHas: StringConstants.theSellerHas,
          StringConstants.weProtectYourPurchase: StringConstants
              .weProtectYourPurchase,
          StringConstants.editAddress: StringConstants.editAddress,
          StringConstants.summary: StringConstants.summary,
          StringConstants.toEdit: StringConstants.toEdit,
          StringConstants.paymentMethod: StringConstants.paymentMethod,
          StringConstants.promotionalCode: StringConstants.promotionalCode,
          StringConstants
              .theTransportCompanyAlreadyHasYourPackage: StringConstants
              .theTransportCompanyAlreadyHasYourPackage,
          StringConstants.weWillNotify: StringConstants.weWillNotify,
          StringConstants.shippingCade: StringConstants.shippingCade,
          StringConstants.knowMore: StringConstants.knowMore,
          StringConstants.protectYour: StringConstants.protectYour,
          StringConstants.followUp: StringConstants.followUp,
          StringConstants.enjoyYourPurchase: StringConstants.enjoyYourPurchase,
          StringConstants.oneThingThanks: StringConstants.oneThingThanks,
          StringConstants.theMoney: StringConstants.theMoney,
        },
        'es_US': {
          StringConstants
              .chooseTheLanguageFamiliarToYou: 'Elige el idioma\nfamiliar para ti.',
          StringConstants.english: 'inglés',
          StringConstants.rot: 'PUDRIR',
          StringConstants.spanish: 'Español ',
          StringConstants.login: 'Iniciar sesión',
          StringConstants.returnMade: 'Regreso hecho',
          StringConstants.orderDetails: 'Detalles del pedido',
          StringConstants.loginWithGoogle: 'Iniciar sesión con Google',
          StringConstants.loginWithFacebook: 'Iniciar sesión con Facebook',
          StringConstants
              .loginWithEmail: 'Iniciar sesión con correo electrónico',
          StringConstants.loginWithPhone: 'Iniciar sesión con teléfono',
          StringConstants.signUpWithPhone: 'Regístrate con el teléfono',
          StringConstants
              .signUpWithEmail: 'Regístrate con el correo electrónico',
          StringConstants.doNotHaveAnAccount: 'No tienes una cuenta?',
          StringConstants.enterYourPhoneNumber: 'Ingrese su número de teléfono',
          StringConstants.enterYourFullName: 'Ingrese su nombre completo',
          StringConstants.enterYourEmail: 'Ingresa tu correo electrónico',
          StringConstants.enterYourGender: 'Ingresa tu género',
          StringConstants.gender: 'Género',
          StringConstants.enterYourDob: 'Entra en tu dob',
          StringConstants
              .enterYourEmailAndPassword: '‘Ingrese su correo electrónico y contraseña’',
          StringConstants.pleaseEnterPassword: 'Ingresar Ingresar Contraseña',
          StringConstants.enterYourFirstName: 'Ingrese su nombre',
          StringConstants.enterYourLastName: 'Ingresa tu apellido',
          StringConstants
              .enterYourSellersAddress: "Ingrese la dirección de su vendedor",
          StringConstants.firstName: 'Nombre',
          StringConstants.lastName: 'Apellido',
          StringConstants.dob: 'Fecha de nacimiento',
          StringConstants.sellersAddress: "Dirección del vendedor",
          StringConstants.resetPassword: 'Restablecer contraseña ?',
          StringConstants.checkYourSms: 'Consulta tus sms',
          StringConstants.checkYourMail: 'Consulta tu correo',
          StringConstants
              .pleasePutYourMobileNumberToResetYourPassword: 'Por favor, ponga su número de móvil para restablecer su contraseña',
          StringConstants
              .pleasePutYourEmailToResetYourPassword: 'Por favor, ponga su correo electrónico para restablecer su contraseña',
          StringConstants.profile: 'Perfil',
          StringConstants.publicInformation: 'Información Pública',
          StringConstants.personalInformation: 'Información Personal',
          StringConstants.reviews: 'Revisiones',
          StringConstants.account: 'Cuenta',
          StringConstants.home: 'Hogar',
          StringConstants.favorites: 'Favoritos',
          StringConstants.chats: 'Chats',
          StringConstants.sales: 'Ventas',
          StringConstants.purchases: 'Compras',
          StringConstants.wallet: 'billete',
          StringConstants.subscription: 'Suscripción',
          StringConstants.generalSetting: 'Escenario general',
          StringConstants.changePassword: 'Cambiar contraseña',
          StringConstants.help: 'Ayuda',
          StringConstants.myQRCode: 'Mi código QR',
          StringConstants.user: 'Usuario',
          StringConstants.following: 'Siguiendo',
          StringConstants.logOut: 'Iniciar sesión',
          StringConstants.signUp: 'Regístrate',
          StringConstants.password: 'Contraseña',
          StringConstants.fullName: 'Nombre completo',
          StringConstants.email: 'correo electrónico',
          StringConstants.assignedRole: 'Rol asignado',
          StringConstants.phoneNumber: 'Número de teléfono',
          StringConstants.passwordReset: 'Restablecimiento de contraseña',
          StringConstants.or: 'O',
          StringConstants.next: 'Siguiente',
          StringConstants.profilePublic: 'Perfil Público',
          StringConstants
              .pleasePutTheSixDigitsSentToYou: '‘Por favor, pon los 6 dígitos que te han enviado’',
          StringConstants.createNewPassword: 'Crear nueva contraseña',
          StringConstants
              .yourNewPasswordMustBeDifferentFromPreviousUsedPasswords: '‘Su nueva contraseña debe ser diferente de las contraseñas utilizadas anteriormente’.',
          StringConstants
              .pleaseEnterNewPassword: 'Por favor ingrese una nueva contraseña',
          StringConstants
              .pleaseEnterConfirmPassword: 'Por favor ingrese confirmar contraseña',
          StringConstants.currentPassword: 'Contraseña actual',
          StringConstants.newPassword: 'Nueva contraseña',
          StringConstants.confirmPassword: 'Confirmar contraseña',
          StringConstants.save: 'Guardar',
          StringConstants.myProfile: 'Mi perfil',
          StringConstants.rateUs: 'Calificarnos',
          StringConstants.welcome: 'Bienvenido,',
          StringConstants.message: 'Mensaje',
          StringConstants.total: 'total',
          StringConstants.productsStatus: 'Estado de los productos',
          StringConstants.notification: 'Notificación',
          StringConstants.upload: 'Subir',
          StringConstants.submit: 'Presentar',
          StringConstants.placeAnAdHere: 'Pon un anuncio aquí.',
          StringConstants.search: 'Buscar',
          StringConstants.cart: 'Carrito',
          StringConstants.welcomeToFertileMate: 'Bienvenido a Fertilemate',
          StringConstants
              .aIDrivenFertilityAnalysis: 'Análisis de fertilidad impulsado por IA',
          StringConstants
              .comprehensiveHealthAssessments: 'Evaluaciones sanitarias integrales',
          StringConstants.boostYourFertilityToday: 'Impulsa tu fertilidad hoy!',
          StringConstants.getStarted: 'Empezar',
          StringConstants
              .yourReproductiveHealthJourney: '‘Tu viaje de salud reproductiva’',
          StringConstants.support: 'Apoyo 24 horas al día, 7 días a la semana',
          StringConstants.supportText: 'Apoyo',
          StringConstants.availableNow: 'Disponible ahora',
          StringConstants.chatNow: 'Chat ahora',
          StringConstants.chat: 'charlar',
          StringConstants.healthAssessment: 'Evaluación de la salud',
          StringConstants.bloodTests: 'Pruebas de sangre',
          StringConstants.result: 'Resultado',
          StringConstants.prediabetesAssessment: 'Evaluación de la Prediabetes',
          StringConstants.document: 'Documento',
          StringConstants.personalInfo: 'Información personal',
          StringConstants.yourName: 'Tu nombre',
          StringConstants.occupation: 'Ocupación',
          StringConstants.employer: 'Empleador',
          StringConstants.usCitizen: 'ciudadano estadounidense',
          StringConstants.contactInfo: 'Información de contacto',
          StringConstants.rotProtection: 'protección ROT',
          StringConstants
              .buyWithoutWorries: 'Compre sin preocupaciones a través de nuestro servicio de envío. Transacción protegida con reembolsos, pagos seguros y ayuda cuando la necesite.',
          StringConstants.edit: 'Editar',
          StringConstants.shareYourOpinion: 'Comparte tu opinión',
          StringConstants
              .yourRatingForThisProductGood: '‘Tu valoración para este producto: Bueno’',
          StringConstants.typeHere: 'Tipo aquí',
          StringConstants.send: 'Enviar',
          StringConstants.categories: 'Categorías',
          StringConstants.seeAll: 'VER TODO',
          StringConstants.reportProduct: 'Informar producto',
          StringConstants.electronics: 'Electrónica',
          StringConstants.nearYou: 'Cerca de ti',
          StringConstants.bestSeller: 'Mejor Vendedor',
          StringConstants.share: 'Compartir',
          StringConstants
              .rotAllRightsReserved: ' RoT Todos los derechos reservados',
          StringConstants.changeOfConsent: 'Cambio de consentimiento',
          StringConstants.privacyPolicies: 'Políticas de privacidad',
          StringConstants.termsAndConditions: 'Términos y Condiciones',
          StringConstants.legalWarning: 'Advertencia legal',
          StringConstants.legal: 'legal',
          StringConstants.coexistenceRules: 'Reglas de convivencia',
          StringConstants.securityAdvice: 'Consejos de seguridad',
          StringConstants.tipsAndRules: 'Consejos y reglas',
          StringConstants.consultationInProgress: '‘Consulta en curso’',
          StringConstants.helpCenter: 'Centro de Ayuda',
          StringConstants.medium: 'Medio',
          StringConstants.addNewAccount: 'Agregar nueva cuenta',
          StringConstants.cars: 'Automóviles',
          StringConstants.motorcycle: 'motocicleta',
          StringConstants.realEstate: 'Bienes Raíces',
          StringConstants.employment: 'Empleo',
          StringConstants.business: 'Negocios',
          StringConstants.services: 'Servicios',
          StringConstants.computer: 'computadora',
          StringConstants.phone: 'teléfono',
          StringConstants.baby: 'Bebé',
          StringConstants.games: 'Juegos',
          StringConstants.fashion: 'Moda',
          StringConstants.sports: 'deportes',
          StringConstants.leisure: 'Ocio ',
          StringConstants.agriculture: 'agricultura',
          StringConstants.community: 'Comunidad',
          StringConstants.training: 'Entrenamiento',
          StringConstants.imageAndSound: 'Imagen y sonido',
          StringConstants.sportsAndNautical: 'Deportes y náutica',
          StringConstants.computerAndElectronic: 'computadora y electrónica',
          StringConstants.hobbiesAndLeisure: 'aficiones y ocio',
          StringConstants.engineAndAccessories: 'Motor y accesorios',
          StringConstants.homeAndGarden: 'Hogar y jardín',
          StringConstants.collecting: 'recoleccionando',
          StringConstants.tourism: 'Turismo',
          StringConstants.description: 'Descripción',
          StringConstants.title: 'Título',
          StringConstants.category: 'Categoría',
          StringConstants.productLocation: 'Ubicación del producto',
          StringConstants.city: 'Ciudad',
          StringConstants.country: 'País',
          StringConstants.zipCode: 'Código postal',
          StringConstants.brand: 'Marca',
          StringConstants.hashtag: 'Hashtag',
          StringConstants.price: 'precio',
          StringConstants.currency: 'Moneda',
          StringConstants.postAdd: 'Publicar agregar',
          StringConstants.hire: 'Contratar',
          StringConstants.rent: 'Alquilar',
          StringConstants.exchange: 'Intercambio',
          StringConstants.buy: 'Comprar',
          StringConstants.learnMore: 'Aprende más',
          StringConstants.sell: 'vender',
          StringConstants.enableShipping: 'Habilitar envío',
          StringConstants.keepExploring: 'Sigue explorando',
          StringConstants.ongoing: 'En curso',
          StringConstants.completed: 'completado',
          StringConstants.inWind: 'En viento',
          StringConstants.inProgress: 'En progreso',
          StringConstants.finished: 'terminado',
          StringConstants.products: 'Productos',
          StringConstants.published: 'Publicado',
          StringConstants.info: 'Información',
          StringConstants.searches: 'Búsquedas',
          StringConstants.friend: 'Amigo',
          StringConstants.editPrice: 'Editar precio',
          StringConstants
              .forSecurity: '‘Por razones de seguridad,\nunca compartas datos privados’',
          StringConstants.getPaid: 'Obtener pago en persona',
          StringConstants.purchasesStatus: 'Estado de las compras',
          StringConstants.twoStepVerification: 'Verificación de dos pasos',
          StringConstants
              .useVerificationMethods: '‘Utilice métodos de verificación para confirmar que la cuenta le pertenece, por ejemplo, iniciando sesión desde un dispositivo desconocido o cambiando su información personal’.',
          StringConstants
              .verifyThatThisAccount: '‘Verifica que esta cuenta te pertenece’',
          StringConstants
              .chooseHowToReceive: '‘Elija cómo recibir el código de verificación’.',
          StringConstants.appUnlock: 'Desbloqueo de aplicación',
          StringConstants.linkedDevices: 'Dispositivos vinculados',
          StringConstants.collaborator: 'Colaborador',
          StringConstants.unlockingTheApp: 'Desbloqueando la aplicación',
          StringConstants
              .youUseTouchId: 'Utiliza Touch ID para acceder a su cuenta.',
          StringConstants.myProducts: 'Mis productos',
          StringConstants.addNewCard: 'Agregar nueva tarjeta',
          StringConstants
              .getNotifiedIfAnyOfYourProductsExpire: 'Obtener notificaciones si alguno de sus productos caduca. ¡Puedes volver a publicarlo!',
          StringConstants.expiredProducts: 'Productos caducados',
          StringConstants.mySearches: 'Mis búsquedas',
          StringConstants.myFavorites: 'Mis favoritos',
          StringConstants.searchAlerts: 'Buscar alertas',
          StringConstants.priceDrop: 'Baja de precios',
          StringConstants.favoritesSold: 'Favoritos vendidos',
          StringConstants.favoritesReserved: 'Favoritos reservados',
          StringConstants.newProducts: 'Nuevos productos',
          StringConstants.additionalOptions: 'Opciones adicionales',
          StringConstants.tipsTndSuggestions: 'Consejos y sugerencias',
          StringConstants.promotionsAndNewFeatures: '‘Promociones y novedades’',
          StringConstants.collaborators: 'Colaboradores',
          StringConstants.somethingWentWrong: 'Algo salió mal',
          StringConstants
              .weAreWorkingToSolveIt: '‘Estamos trabajando para resolverlo’.',
          StringConstants
              .ifTheProblemPersists: '‘Si el problema persiste, puedes reportarlo en la sección Ayuda con el siguiente código:’:',
          StringConstants.code: 'Código: ',
          StringConstants.retry: 'Retroceso',
          StringConstants.useAnotherMethod: 'Utilice otro método',
          StringConstants.eliminate: 'Eliminar',
          StringConstants.readyWeSendYour: 'Listo! Enviamos tu invitación a',
          StringConstants
              .theInvitationIsValidUntilSunday: 'La invitación es válida hasta el domingo 4 de febrero. Una vez que lo aceptes, podrás empezar a colaborar en tu cuenta.',
          StringConstants.resendInvitation: 'Renviar invitación',
          StringConstants.createAnotherInvitation: 'Crear otra invitación',
          StringConstants.seeYourCollaborators: '‘Vea a sus colaboradores’',
          StringConstants.seeDetails: 'Ver detalles',
          StringConstants.inviteCollaborator: 'Invitar colaborador',
          StringConstants.manageRoles: 'Gestionar roles',
          StringConstants
              .enterTheEmailOfTheCollaborator: '‘Entra en el email del colaborador al que quieres invitar’',
          StringConstants
              .keepInMindThatYourEmailMust: '‘Ten en cuenta que tu correo electrónico no debe estar registrado en Mercado Pago o Mercado Libre, porque lo utilizarás exclusivamente para tu negocio’.',
          StringConstants.continueText: 'Continuar',
          StringConstants.protectedByReCAPTCHA: 'Protegido por reCAPTCHA-',
          StringConstants.privacy: 'Privacidad',
          StringConstants.chooseARole: 'Elige un papel',
          StringConstants
              .enterTheVerificationCode: '‘Ingrese el código de verificación’',
          StringConstants
              .youReceived: '‘Recibiste un número de 6 dígitos a través de WhatsApp’.',
          StringConstants.resendCode: 'Renviar código',
          StringConstants.administrator: 'Administrador',
          StringConstants.supervisor: 'Supervisor',
          StringConstants.createNewRole: 'Crear nuevo papel',
          StringConstants.goBack: 'Regresar',
          StringConstants.accounts: 'Cuentas',
          StringConstants.recharge: 'Recargar',
          StringConstants.charge: 'Cargar',
          StringConstants.sendMoney: 'Envía dinero',
          StringConstants.pay: 'pagar',
          StringConstants.withdraw: 'Retirar',
          StringConstants.historyOfMovements: 'Historia de los movimientos',
          StringConstants.bankInformation: 'Información bancaria',
          StringConstants.confirm: 'Confirmar',
          StringConstants.editRolePermissions: 'Editar permisos de rol',
          StringConstants.changeEmail: 'Cambiar correo electrónico',
          StringConstants.changeRole: 'Cambiar rol',
          StringConstants.iAcceptThe: 'Acepto el ',
          StringConstants.converter: 'Convertidor',
          StringConstants
              .forTheUseOfTheCollaboratorsTool: ' ‘para el uso de la herramienta Colaboradores’.',
          StringConstants.cancel: 'Cancelar',
          StringConstants.keepInWallet: 'Mantén la cartera',
          StringConstants.withdrawBalance: 'Retirar saldo',
          StringConstants
              .useTheConverter: '‘Usar el convertidor para comparar valores actuales’',
          StringConstants.conditions: 'Condiciones',
          StringConstants.sendInvitation: 'Enviar invitación',
          StringConstants.rotPro: 'ROTPRO',
          StringConstants.addNew: 'Agregar nuevo',
          StringConstants.departures: 'Salidas',
          StringConstants.appetizer: 'Apetizador',
          StringConstants.all: 'todo',
          StringConstants.local: 'local',
          StringConstants.swift: 'Rápido',
          StringConstants.bicSwiftCode: 'ERAN',
          StringConstants.bankNameAndAddress: 'Nombre y dirección del banco',
          StringConstants.recipient: 'Receptor',
          StringConstants
              .useThisData: '‘Utilice estos datos para recibir su salario y transferencias desde una cuenta bancaria en euros’.',
          StringConstants
              .provideThisData: 'Proporcionar estos datos a las empresas para que establezcan adeudos domiciliados y liquiden automáticamente facturas recurrentes',
          StringConstants
              .ifTheIssuingBank: 'Si el banco emisor admite pagos instantáneos, el pago llegará en cuestión de segundos. Si no, tardará hasta 2 días hábiles.',
          StringConstants
              .ifYourEmployer: 'Si su empleador o una empresa rechaza su IBAN porque no es "local", es ilegal. Descubre qué puedes hacer en nuestro blog.',
          StringConstants.documents: 'Documentos',
          StringConstants.bankStatement: 'Declaración bancaria',
          StringConstants.accountConfirmation: 'Confirmación de cuenta',
          StringConstants
              .onlyForInternationalTransfers: '‘Solo para transferencias internacionales’',
          StringConstants.onlyForLocalTransfers: 'ERAN',
          StringConstants.currencyAccount: 'Sólo para transferencias locales',
          StringConstants.flexibleAccount: 'Cuenta Moneda',
          StringConstants.pockets: 'Cuenta flexible',
          StringConstants.saveMoneyAndManage: 'bolsillos',
          StringConstants
              .jointAccount: '‘Guarda dinero y administralo por tu cuenta > o con amigos’',
          StringConstants.anAccountForAllTypes: 'Cuenta Conjunta',
          StringConstants
              .getUpTo: '‘Una cuenta para todo tipo de dúos, con IBAN y tarjetas’',
          StringConstants
              .proAccount: 'Llegar hasta el 5,39%. Revolut Securities Europe UAB proporciona este servicio',
          StringConstants.howMuchMoneyDoYouWantToRecharge: 'Cuenta profesional',
          StringConstants
              .rateAccordingToTheAmountOfTheRecharge: '‘¿Cuánto dinero quieres recargar?’?',
          StringConstants
              .reloadWallet: '‘Tarifa según el importe de la recarga’',
          StringConstants.transferToBank: 'Cargar billetera',
          StringConstants.howMuchMoney: 'Transferencia a banco',
          StringConstants
              .rechargeSummary: '‘¿Cuánto dinero quieres transferir?’?',
          StringConstants.rechargeFee: 'Resumen de recarga',
          StringConstants.rechargeCarriedOut: 'Tarifa de recarga',
          StringConstants.goToWallet: 'Recargo realizado',
          StringConstants.theMoneyIsAlready: 'Ir a la billetera',
          StringConstants
              .aReadyToUse: 'El dinero ya está en tu billetera. Disfruta de tus próximas compras en ROT.',
          StringConstants
              .credit: 'Una cuenta comercial lista para usar con hasta un 1,2% de reembolso',
          StringConstants.discoverLoansAndCreditCards: 'crédito',
          StringConstants
              .accountGreaterThanEighteen: '‘Descubre préstamos y tarjetas de crédito’',
          StringConstants.linkedAccount: 'Cuenta <18',
          StringConstants
              .checkAllYourBankAccountsInOnePlace: 'Cuenta vinculada',
          StringConstants
              .accountsForChildren: '‘Consulta todas tus cuentas bancarias en un solo lugar’',
          StringConstants
              .moreThanThirtyCurrencies: '‘Cuentas para niños y adolescentes entre 6 y 17 años’',
          StringConstants
              .itOffersYouSolutions: '‘Más de 30 monedas para que puedas pagar en casa incluso en el extranjero’',
          StringConstants
              .findTheBestSubscription: '‘Te ofrece soluciones para vender más, facturar, rastrear inventario, todo en una sola aplicación y muchas más ventajas’.',
          StringConstants
              .searchForCollaborator: '‘¡Encuentra el mejor plan de suscripción que mejor se adapte a tus objetivos!’!',
          StringConstants
              .getNotifiedWhenNewProductsFit: 'Búsqueda de colaborador',
          StringConstants
              .getNotifiedAboutAnyNewsRegarding: 'Obtener notificaciones cuando los nuevos productos se ajusten a sus criterios de búsqueda',
          StringConstants
              .getNotifiedAboutPromotionsAndOther: '‘Obtener notificaciones sobre cualquier novedad con respecto a sus productos favoritos y vendedores’.',
          StringConstants.payment:'Pago',
          StringConstants.cardNumber:"Número de tarjeta",
          StringConstants.enterDigitCardNumber:"Ingrese el número de tarjeta de 12 dígitos",
          StringConstants.validThru:"Válido a través",
          StringConstants.cvv:"CVV",
          StringConstants.month:"mes",
          StringConstants.year:"año",
          StringConstants.ok:"Está bien",
          StringConstants.cardHoldersName:"Nombre del Titular de la Tarjeta",
          StringConstants.nameOnCard:"Nombre de la tarjeta",
          StringConstants.payMyFriend:'Paga a mi amigo',
          StringConstants.cardPayment:'Pago de Tarjetas',
          StringConstants.available:'Disponible',
          StringConstants.youPay:'tú pagas',
          StringConstants.address:'Dirección',
          StringConstants.streetNameAndNumber:'Nombre y número de la calle',
          StringConstants.floorAndDoorNumber:'Número de piso y puerta',
          StringConstants.nearbyPoints:'Puntos cercanos',
          StringConstants.inPerson:'En persona',
          StringConstants.meetAndPay:'‘Conoce y paga sin salir de la app cuando estés con el vendedor’',
          StringConstants.pickUpPoint:'Punto de recogida',
          StringConstants.viewPickUpPoint:'Ver puntos de recogida',
          StringConstants.myAddress:'Mi dirección',
          StringConstants.colour:'Color:',
          StringConstants.deliveryExpectedIn:'Entrega esperada',
          StringConstants.purchaseMade:'Compra realizada',
          StringConstants.theSellerHas:'‘El vendedor tiene 24 horas para confirmar que enviará’.',
          StringConstants.weProtectYourPurchase:'Protegemos su compra con RoT Protection. Lea cómo funciona',
          StringConstants.editAddress:'Editar dirección',
          StringConstants.summary:'Resumen',
          StringConstants.toEdit:'Editar',
          StringConstants.paymentMethod:'Método de pago',
          StringConstants.promotionalCode:'Código promocional',
          StringConstants.theTransportCompanyAlreadyHasYourPackage:'‘La empresa de transporte ya tiene su paquete’.',
          StringConstants.weWillNotify:'‘Le avisaremos cuando el paquete esté en entrega, hay menos para ga’',
          StringConstants.shippingCade:'cade marítimo',
          StringConstants.knowMore:'Sabes más',
          StringConstants.protectYour:'‘Protege tu compra con esa protección PRO’',
          StringConstants.followUp:'Seguir',
          StringConstants.enjoyYourPurchase:'Disfruta de tu compra',
          StringConstants.oneThingThanks:'‘Una cosa gracias por hacer de este mundo un lugar un poco mejor’.',
          StringConstants.theMoney:'El dinero que pagaste con la billetera ya está en tu cuenta. Recibirá el resto en el método que utilizó en un plazo de 24 a 48 horas',
        },
      };
}
