import 'package:get/get.dart';

import '../app/data/constants/string_constants.dart';

class LanguageTranslate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          StringConstants.chooseTheLanguageFamiliarToYou:
              StringConstants.chooseTheLanguageFamiliarToYou,
          StringConstants.english: StringConstants.english,
          StringConstants.rot: StringConstants.rot,
          StringConstants.spanish: StringConstants.spanish,
          StringConstants.login: StringConstants.login,
          StringConstants.returnMade: StringConstants.returnMade,
          StringConstants.orderDetails: StringConstants.orderDetails,
          StringConstants.loginWithGoogle: StringConstants.loginWithGoogle,
          StringConstants.loginWithFacebook: StringConstants.loginWithFacebook,
          StringConstants.loginWithEmail: StringConstants.loginWithEmail,
          StringConstants.loginWithPhone: StringConstants.loginWithPhone,
          StringConstants.signUpWithPhone: StringConstants.signUpWithPhone,
          StringConstants.signUpWithEmail: StringConstants.signUpWithEmail,
          StringConstants.doNotHaveAnAccount:
              StringConstants.doNotHaveAnAccount,
          StringConstants.enterYourPhoneNumber:
              StringConstants.enterYourPhoneNumber,
          StringConstants.enterYourFullName: StringConstants.enterYourFullName,
          StringConstants.enterYourEmail: StringConstants.enterYourEmail,
          StringConstants.enterYourGender: StringConstants.enterYourGender,
          StringConstants.gender: StringConstants.gender,
          StringConstants.enterYourDob: StringConstants.enterYourDob,
          StringConstants.enterYourEmailAndPassword:
              StringConstants.enterYourEmailAndPassword,
          StringConstants.pleaseEnterPassword:
              StringConstants.pleaseEnterPassword,
          StringConstants.enterYourFirstName:
              StringConstants.enterYourFirstName,
          StringConstants.enterYourLastName: StringConstants.enterYourLastName,
          StringConstants.enterYourSellersAddress:
              StringConstants.enterYourSellersAddress,
          StringConstants.firstName: StringConstants.firstName,
          StringConstants.lastName: StringConstants.lastName,
          StringConstants.dob: StringConstants.dob,
          StringConstants.sellersAddress: StringConstants.sellersAddress,
          StringConstants.resetPassword: StringConstants.resetPassword,
          StringConstants.checkYourSms: StringConstants.checkYourSms,
          StringConstants.checkYourMail: StringConstants.checkYourMail,
          StringConstants.pleasePutYourMobileNumberToResetYourPassword:
              StringConstants.pleasePutYourMobileNumberToResetYourPassword,
          StringConstants.pleasePutYourEmailToResetYourPassword:
              StringConstants.pleasePutYourEmailToResetYourPassword,
          StringConstants.profile: StringConstants.profile,
          StringConstants.publicInformation: StringConstants.publicInformation,
          StringConstants.personalInformation:
              StringConstants.personalInformation,
          StringConstants.reviews: StringConstants.reviews,
          StringConstants.account: StringConstants.account,
          StringConstants.home: StringConstants.home,
          StringConstants.favorites: StringConstants.favorites,
          StringConstants.chats: StringConstants.chats,
          StringConstants.sales: StringConstants.sales,
          StringConstants.purchases: StringConstants.purchases,
          StringConstants.wallet: StringConstants.wallet,
          StringConstants.subscription: StringConstants.subscription,
          StringConstants.generalSetting: StringConstants.generalSetting,
          StringConstants.changePassword: StringConstants.changePassword,
          StringConstants.help: StringConstants.help,
          StringConstants.myQRCode: StringConstants.myQRCode,
          StringConstants.user: StringConstants.user,
          StringConstants.following: StringConstants.following,
          StringConstants.logOut: StringConstants.logOut,
          StringConstants.signUp: StringConstants.signUp,
          StringConstants.password: StringConstants.password,
          StringConstants.fullName: StringConstants.fullName,
          StringConstants.email: StringConstants.email,
          StringConstants.assignedRole: StringConstants.assignedRole,
          StringConstants.phoneNumber: StringConstants.phoneNumber,
          StringConstants.passwordReset: StringConstants.passwordReset,
          StringConstants.or: StringConstants.or,
          StringConstants.next: StringConstants.next,
          StringConstants.profilePublic: StringConstants.profilePublic,
          StringConstants.pleasePutTheSixDigitsSentToYou:
              StringConstants.pleasePutTheSixDigitsSentToYou,
          StringConstants.createNewPassword: StringConstants.createNewPassword,
          StringConstants
                  .yourNewPasswordMustBeDifferentFromPreviousUsedPasswords:
              StringConstants
                  .yourNewPasswordMustBeDifferentFromPreviousUsedPasswords,
          StringConstants.pleaseEnterNewPassword:
              StringConstants.pleaseEnterNewPassword,
          StringConstants.pleaseEnterConfirmPassword:
              StringConstants.pleaseEnterConfirmPassword,
          StringConstants.currentPassword: StringConstants.currentPassword,
          StringConstants.newPassword: StringConstants.newPassword,
          StringConstants.confirmPassword: StringConstants.confirmPassword,
          StringConstants.save: StringConstants.save,
          StringConstants.myProfile: StringConstants.myProfile,
          StringConstants.rateUs: StringConstants.rateUs,
          StringConstants.welcome: StringConstants.welcome,
          StringConstants.message: StringConstants.message,
          StringConstants.total: StringConstants.total,
          StringConstants.productsStatus: StringConstants.productsStatus,
          StringConstants.notification: StringConstants.notification,
          StringConstants.upload: StringConstants.upload,
          StringConstants.submit: StringConstants.submit,
          StringConstants.placeAnAdHere: StringConstants.placeAnAdHere,
          StringConstants.search: StringConstants.search,
          StringConstants.cart: StringConstants.cart,
          StringConstants.welcomeToFertileMate:
              StringConstants.welcomeToFertileMate,
          StringConstants.aIDrivenFertilityAnalysis:
              StringConstants.aIDrivenFertilityAnalysis,
          StringConstants.comprehensiveHealthAssessments:
              StringConstants.comprehensiveHealthAssessments,
          StringConstants.boostYourFertilityToday:
              StringConstants.boostYourFertilityToday,
          StringConstants.getStarted: StringConstants.getStarted,
          StringConstants.yourReproductiveHealthJourney:
              StringConstants.yourReproductiveHealthJourney,
          StringConstants.support: StringConstants.support,
          StringConstants.supportText: StringConstants.supportText,
          StringConstants.availableNow: StringConstants.availableNow,
          StringConstants.chatNow: StringConstants.chatNow,
          StringConstants.chat: StringConstants.chat,
          StringConstants.healthAssessment: StringConstants.healthAssessment,
          StringConstants.bloodTests: StringConstants.bloodTests,
          StringConstants.result: StringConstants.result,
          StringConstants.prediabetesAssessment:
              StringConstants.prediabetesAssessment,
          StringConstants.document: StringConstants.document,
          StringConstants.personalInfo: StringConstants.personalInfo,
          StringConstants.yourName: StringConstants.yourName,
          StringConstants.occupation: StringConstants.occupation,
          StringConstants.employer: StringConstants.employer,
          StringConstants.usCitizen: StringConstants.usCitizen,
          StringConstants.contactInfo: StringConstants.contactInfo,
          StringConstants.rotProtection: StringConstants.rotProtection,
          StringConstants.buyWithoutWorries: StringConstants.buyWithoutWorries,
          StringConstants.edit: StringConstants.edit,
          StringConstants.shareYourOpinion: StringConstants.shareYourOpinion,
          StringConstants.yourRatingForThisProductGood:
              StringConstants.yourRatingForThisProductGood,
          StringConstants.typeHere: StringConstants.typeHere,
          StringConstants.send: StringConstants.send,
          StringConstants.categories: StringConstants.categories,
          StringConstants.seeAll: StringConstants.seeAll,
          StringConstants.reportProduct: StringConstants.reportProduct,
          StringConstants.electronics: StringConstants.electronics,
          StringConstants.nearYou: StringConstants.nearYou,
          StringConstants.bestSeller: StringConstants.bestSeller,
          StringConstants.share: StringConstants.share,
          StringConstants.rotAllRightsReserved:
              StringConstants.rotAllRightsReserved,
          StringConstants.changeOfConsent: StringConstants.changeOfConsent,
          StringConstants.privacyPolicies: StringConstants.privacyPolicies,
          StringConstants.termsAndConditions:
              StringConstants.termsAndConditions,
          StringConstants.legalWarning: StringConstants.legalWarning,
          StringConstants.legal: StringConstants.legal,
          StringConstants.coexistenceRules: StringConstants.coexistenceRules,
          StringConstants.securityAdvice: StringConstants.securityAdvice,
          StringConstants.tipsAndRules: StringConstants.tipsAndRules,
          StringConstants.consultationInProgress:
              StringConstants.consultationInProgress,
          StringConstants.helpCenter: StringConstants.helpCenter,
          StringConstants.medium: StringConstants.medium,
          StringConstants.addNewAccount: StringConstants.addNewAccount,
          StringConstants.cars: StringConstants.cars,
          StringConstants.motorcycle: StringConstants.motorcycle,
          StringConstants.realEstate: StringConstants.realEstate,
          StringConstants.employment: StringConstants.employment,
          StringConstants.business: StringConstants.business,
          StringConstants.services: StringConstants.services,
          StringConstants.computer: StringConstants.computer,
          StringConstants.phone: StringConstants.phone,
          StringConstants.baby: StringConstants.baby,
          StringConstants.games: StringConstants.games,
          StringConstants.fashion: StringConstants.fashion,
          StringConstants.sports: StringConstants.sports,
          StringConstants.leisure: StringConstants.leisure,
          StringConstants.agriculture: StringConstants.agriculture,
          StringConstants.community: StringConstants.community,
          StringConstants.training: StringConstants.training,
          StringConstants.imageAndSound: StringConstants.imageAndSound,
          StringConstants.sportsAndNautical: StringConstants.sportsAndNautical,
          StringConstants.computerAndElectronic:
              StringConstants.computerAndElectronic,
          StringConstants.hobbiesAndLeisure: StringConstants.hobbiesAndLeisure,
          StringConstants.engineAndAccessories:
              StringConstants.engineAndAccessories,
          StringConstants.homeAndGarden: StringConstants.homeAndGarden,
          StringConstants.collecting: StringConstants.collecting,
          StringConstants.tourism: StringConstants.tourism,
          StringConstants.description: StringConstants.description,
          StringConstants.title: StringConstants.title,
          StringConstants.category: StringConstants.category,
          StringConstants.productLocation: StringConstants.productLocation,
          StringConstants.city: StringConstants.city,
          StringConstants.country: StringConstants.country,
          StringConstants.zipCode: StringConstants.zipCode,
          StringConstants.brand: StringConstants.brand,
          StringConstants.hashtag: StringConstants.hashtag,
          StringConstants.price: StringConstants.price,
          StringConstants.currency: StringConstants.currency,
          StringConstants.postAdd: StringConstants.postAdd,
          StringConstants.hire: StringConstants.hire,
          StringConstants.rent: StringConstants.rent,
          StringConstants.exchange: StringConstants.exchange,
          StringConstants.buy: StringConstants.buy,
          StringConstants.learnMore: StringConstants.learnMore,
          StringConstants.sell: StringConstants.sell,
          StringConstants.enableShipping: StringConstants.enableShipping,
          StringConstants.keepExploring: StringConstants.keepExploring,
          StringConstants.ongoing: StringConstants.ongoing,
          StringConstants.completed: StringConstants.completed,
          StringConstants.inWind: StringConstants.inWind,
          StringConstants.inProgress: StringConstants.inProgress,
          StringConstants.finished: StringConstants.finished,
          StringConstants.products: StringConstants.products,
          StringConstants.published: StringConstants.published,
          StringConstants.info: StringConstants.info,
          StringConstants.searches: StringConstants.searches,
          StringConstants.friend: StringConstants.friend,
          StringConstants.editPrice: StringConstants.editPrice,
          StringConstants.forSecurity: StringConstants.forSecurity,
          StringConstants.getPaid: StringConstants.getPaid,
          StringConstants.purchasesStatus: StringConstants.purchasesStatus,
          StringConstants.twoStepVerification:
              StringConstants.twoStepVerification,
          StringConstants.useVerificationMethods:
              StringConstants.useVerificationMethods,
          StringConstants.verifyThatThisAccount:
              StringConstants.verifyThatThisAccount,
          StringConstants.chooseHowToReceive:
              StringConstants.chooseHowToReceive,
          StringConstants.appUnlock: StringConstants.appUnlock,
          StringConstants.linkedDevices: StringConstants.linkedDevices,
          StringConstants.collaborator: StringConstants.collaborator,
          StringConstants.unlockingTheApp: StringConstants.unlockingTheApp,
          StringConstants.youUseTouchId: StringConstants.youUseTouchId,
          StringConstants.myProducts: StringConstants.myProducts,
          StringConstants.addNewCard: StringConstants.addNewCard,
          StringConstants.getNotifiedIfAnyOfYourProductsExpire:
              StringConstants.getNotifiedIfAnyOfYourProductsExpire,
          StringConstants.expiredProducts: StringConstants.expiredProducts,
          StringConstants.mySearches: StringConstants.mySearches,
          StringConstants.myFavorites: StringConstants.myFavorites,
          StringConstants.searchAlerts: StringConstants.searchAlerts,
          StringConstants.priceDrop: StringConstants.priceDrop,
          StringConstants.favoritesSold: StringConstants.favoritesSold,
          StringConstants.favoritesReserved: StringConstants.favoritesReserved,
          StringConstants.newProducts: StringConstants.newProducts,
          StringConstants.additionalOptions: StringConstants.additionalOptions,
          StringConstants.tipsTndSuggestions:
              StringConstants.tipsTndSuggestions,
          StringConstants.promotionsAndNewFeatures:
              StringConstants.promotionsAndNewFeatures,
          StringConstants.collaborators: StringConstants.collaborators,
          StringConstants.somethingWentWrong:
              StringConstants.somethingWentWrong,
          StringConstants.weAreWorkingToSolveIt:
              StringConstants.weAreWorkingToSolveIt,
          StringConstants.ifTheProblemPersists:
              StringConstants.ifTheProblemPersists,
          StringConstants.code: StringConstants.code,
          StringConstants.retry: StringConstants.retry,
          StringConstants.useAnotherMethod: StringConstants.useAnotherMethod,
          StringConstants.eliminate: StringConstants.eliminate,
          StringConstants.readyWeSendYour: StringConstants.readyWeSendYour,
          StringConstants.theInvitationIsValidUntilSunday:
              StringConstants.theInvitationIsValidUntilSunday,
          StringConstants.resendInvitation: StringConstants.resendInvitation,
          StringConstants.createAnotherInvitation:
              StringConstants.createAnotherInvitation,
          StringConstants.seeYourCollaborators:
              StringConstants.seeYourCollaborators,
          StringConstants.seeDetails: StringConstants.seeDetails,
          StringConstants.inviteCollaborator:
              StringConstants.inviteCollaborator,
          StringConstants.manageRoles: StringConstants.manageRoles,
          StringConstants.enterTheEmailOfTheCollaborator:
              StringConstants.enterTheEmailOfTheCollaborator,
          StringConstants.keepInMindThatYourEmailMust:
              StringConstants.keepInMindThatYourEmailMust,
          StringConstants.continueText: StringConstants.continueText,
          StringConstants.protectedByReCAPTCHA:
              StringConstants.protectedByReCAPTCHA,
          StringConstants.privacy: StringConstants.privacy,
          StringConstants.chooseARole: StringConstants.chooseARole,
          StringConstants.enterTheVerificationCode:
              StringConstants.enterTheVerificationCode,
          StringConstants.youReceived: StringConstants.youReceived,
          StringConstants.resendCode: StringConstants.resendCode,
          StringConstants.administrator: StringConstants.administrator,
          StringConstants.supervisor: StringConstants.supervisor,
          StringConstants.createNewRole: StringConstants.createNewRole,
          StringConstants.goBack: StringConstants.goBack,
          StringConstants.accounts: StringConstants.accounts,
          StringConstants.recharge: StringConstants.recharge,
          StringConstants.charge: StringConstants.charge,
          StringConstants.sendMoney: StringConstants.sendMoney,
          StringConstants.pay: StringConstants.pay,
          StringConstants.withdraw: StringConstants.withdraw,
          StringConstants.historyOfMovements:
              StringConstants.historyOfMovements,
          StringConstants.bankInformation: StringConstants.bankInformation,
          StringConstants.confirm: StringConstants.confirm,
          StringConstants.editRolePermissions:
              StringConstants.editRolePermissions,
          StringConstants.changeEmail: StringConstants.changeEmail,
          StringConstants.changeRole: StringConstants.changeRole,
          StringConstants.iAcceptThe: StringConstants.iAcceptThe,
          StringConstants.converter: StringConstants.converter,
          StringConstants.forTheUseOfTheCollaboratorsTool:
              StringConstants.forTheUseOfTheCollaboratorsTool,
          StringConstants.cancel: StringConstants.cancel,
          StringConstants.keepInWallet: StringConstants.keepInWallet,
          StringConstants.withdrawBalance: StringConstants.withdrawBalance,
          StringConstants.useTheConverter: StringConstants.useTheConverter,
          StringConstants.conditions: StringConstants.conditions,
          StringConstants.sendInvitation: StringConstants.sendInvitation,
          StringConstants.rotPro: StringConstants.rotPro,
          StringConstants.addNew: StringConstants.addNew,
          StringConstants.departures: StringConstants.departures,
          StringConstants.appetizer: StringConstants.appetizer,
          StringConstants.all: StringConstants.all,
          StringConstants.local: StringConstants.local,
          StringConstants.swift: StringConstants.swift,
          StringConstants.bicSwiftCode: StringConstants.bicSwiftCode,
          StringConstants.bankNameAndAddress:
              StringConstants.bankNameAndAddress,
          StringConstants.recipient: StringConstants.recipient,
          StringConstants.useThisData: StringConstants.useThisData,
          StringConstants.provideThisData: StringConstants.provideThisData,
          StringConstants.ifTheIssuingBank: StringConstants.ifTheIssuingBank,
          StringConstants.ifYourEmployer: StringConstants.ifYourEmployer,
          StringConstants.documents: StringConstants.documents,
          StringConstants.bankStatement: StringConstants.bankStatement,
          StringConstants.accountConfirmation:
              StringConstants.accountConfirmation,
          StringConstants.onlyForInternationalTransfers:
              StringConstants.onlyForInternationalTransfers,
          StringConstants.were: StringConstants.were,
          StringConstants.onlyForLocalTransfers:
              StringConstants.onlyForLocalTransfers,
          StringConstants.currencyAccount: StringConstants.currencyAccount,
          StringConstants.flexibleAccount: StringConstants.flexibleAccount,
          StringConstants.pockets: StringConstants.pockets,
          StringConstants.saveMoneyAndManage:
              StringConstants.saveMoneyAndManage,
          StringConstants.jointAccount: StringConstants.jointAccount,
          StringConstants.anAccountForAllTypes:
              StringConstants.anAccountForAllTypes,
          StringConstants.getUpTo: StringConstants.getUpTo,
          StringConstants.proAccount: StringConstants.proAccount,
          StringConstants.howMuchMoneyDoYouWantToRecharge:
              StringConstants.howMuchMoneyDoYouWantToRecharge,
          StringConstants.rateAccordingToTheAmountOfTheRecharge:
              StringConstants.rateAccordingToTheAmountOfTheRecharge,
          StringConstants.reloadWallet: StringConstants.reloadWallet,
          StringConstants.transferToBank: StringConstants.transferToBank,
          StringConstants.howMuchMoney: StringConstants.howMuchMoney,
          StringConstants.rechargeSummary: StringConstants.rechargeSummary,
          StringConstants.rechargeFee: StringConstants.rechargeFee,
          StringConstants.rechargeCarriedOut:
              StringConstants.rechargeCarriedOut,
          StringConstants.goToWallet: StringConstants.goToWallet,
          StringConstants.theMoneyIsAlready: StringConstants.theMoneyIsAlready,
          StringConstants.aReadyToUse: StringConstants.aReadyToUse,
          StringConstants.credit: StringConstants.credit,
          StringConstants.discoverLoansAndCreditCards:
              StringConstants.discoverLoansAndCreditCards,
          StringConstants.accountGreaterThanEighteen:
              StringConstants.accountGreaterThanEighteen,
          StringConstants.linkedAccount: StringConstants.linkedAccount,
          StringConstants.checkAllYourBankAccountsInOnePlace:
              StringConstants.checkAllYourBankAccountsInOnePlace,
          StringConstants.accountsForChildren:
              StringConstants.accountsForChildren,
          StringConstants.moreThanThirtyCurrencies:
              StringConstants.moreThanThirtyCurrencies,
          StringConstants.itOffersYouSolutions:
              StringConstants.itOffersYouSolutions,
          StringConstants.findTheBestSubscription:
              StringConstants.findTheBestSubscription,
          StringConstants.searchForCollaborator:
              StringConstants.searchForCollaborator,
          StringConstants.getNotifiedWhenNewProductsFit:
              StringConstants.getNotifiedWhenNewProductsFit,
          StringConstants.getNotifiedAboutAnyNewsRegarding:
              StringConstants.getNotifiedAboutAnyNewsRegarding,
          StringConstants.getNotifiedAboutPromotionsAndOther:
              StringConstants.getNotifiedAboutPromotionsAndOther,
        },
        'es_US': {
          StringConstants.chooseTheLanguageFamiliarToYou:
              StringConstants.chooseTheLanguageFamiliarToYou,
          StringConstants.english: StringConstants.english,
          StringConstants.rot: StringConstants.rot,
          StringConstants.spanish: StringConstants.spanish,
          StringConstants.login: StringConstants.login,
          StringConstants.returnMade: StringConstants.returnMade,
          StringConstants.orderDetails: StringConstants.orderDetails,
          StringConstants.loginWithGoogle: StringConstants.loginWithGoogle,
          StringConstants.loginWithFacebook: StringConstants.loginWithFacebook,
          StringConstants.loginWithEmail: StringConstants.loginWithEmail,
          StringConstants.loginWithPhone: StringConstants.loginWithPhone,
          StringConstants.signUpWithPhone: StringConstants.signUpWithPhone,
          StringConstants.signUpWithEmail: StringConstants.signUpWithEmail,
          StringConstants.doNotHaveAnAccount:
              StringConstants.doNotHaveAnAccount,
          StringConstants.enterYourPhoneNumber:
              StringConstants.enterYourPhoneNumber,
          StringConstants.enterYourFullName: StringConstants.enterYourFullName,
          StringConstants.enterYourEmail: StringConstants.enterYourEmail,
          StringConstants.enterYourGender: StringConstants.enterYourGender,
          StringConstants.gender: StringConstants.gender,
          StringConstants.enterYourDob: StringConstants.enterYourDob,
          StringConstants.enterYourEmailAndPassword:
              StringConstants.enterYourEmailAndPassword,
          StringConstants.pleaseEnterPassword:
              StringConstants.pleaseEnterPassword,
          StringConstants.enterYourFirstName:
              StringConstants.enterYourFirstName,
          StringConstants.enterYourLastName: StringConstants.enterYourLastName,
          StringConstants.enterYourSellersAddress:
              StringConstants.enterYourSellersAddress,
          StringConstants.firstName: StringConstants.firstName,
          StringConstants.lastName: StringConstants.lastName,
          StringConstants.dob: StringConstants.dob,
          StringConstants.sellersAddress: StringConstants.sellersAddress,
          StringConstants.resetPassword: StringConstants.resetPassword,
          StringConstants.checkYourSms: StringConstants.checkYourSms,
          StringConstants.checkYourMail: StringConstants.checkYourMail,
          StringConstants.pleasePutYourMobileNumberToResetYourPassword:
              StringConstants.pleasePutYourMobileNumberToResetYourPassword,
          StringConstants.pleasePutYourEmailToResetYourPassword:
              StringConstants.pleasePutYourEmailToResetYourPassword,
          StringConstants.profile: StringConstants.profile,
          StringConstants.publicInformation: StringConstants.publicInformation,
          StringConstants.personalInformation:
              StringConstants.personalInformation,
          StringConstants.reviews: StringConstants.reviews,
          StringConstants.account: StringConstants.account,
          StringConstants.home: StringConstants.home,
          StringConstants.favorites: StringConstants.favorites,
          StringConstants.chats: StringConstants.chats,
          StringConstants.sales: StringConstants.sales,
          StringConstants.purchases: StringConstants.purchases,
          StringConstants.wallet: StringConstants.wallet,
          StringConstants.subscription: StringConstants.subscription,
          StringConstants.generalSetting: StringConstants.generalSetting,
          StringConstants.changePassword: StringConstants.changePassword,
          StringConstants.help: StringConstants.help,
          StringConstants.myQRCode: StringConstants.myQRCode,
          StringConstants.user: StringConstants.user,
          StringConstants.following: StringConstants.following,
          StringConstants.logOut: StringConstants.logOut,
          StringConstants.signUp: StringConstants.signUp,
          StringConstants.password: StringConstants.password,
          StringConstants.fullName: StringConstants.fullName,
          StringConstants.email: StringConstants.email,
          StringConstants.assignedRole: StringConstants.assignedRole,
          StringConstants.phoneNumber: StringConstants.phoneNumber,
          StringConstants.passwordReset: StringConstants.passwordReset,
          StringConstants.or: StringConstants.or,
          StringConstants.next: StringConstants.next,
          StringConstants.profilePublic: StringConstants.profilePublic,
          StringConstants.pleasePutTheSixDigitsSentToYou:
              StringConstants.pleasePutTheSixDigitsSentToYou,
          StringConstants.createNewPassword: StringConstants.createNewPassword,
          StringConstants
                  .yourNewPasswordMustBeDifferentFromPreviousUsedPasswords:
              StringConstants
                  .yourNewPasswordMustBeDifferentFromPreviousUsedPasswords,
          StringConstants.pleaseEnterNewPassword:
              StringConstants.pleaseEnterNewPassword,
          StringConstants.pleaseEnterConfirmPassword:
              StringConstants.pleaseEnterConfirmPassword,
          StringConstants.currentPassword: StringConstants.currentPassword,
          StringConstants.newPassword: StringConstants.newPassword,
          StringConstants.confirmPassword: StringConstants.confirmPassword,
          StringConstants.save: StringConstants.save,
          StringConstants.myProfile: StringConstants.myProfile,
          StringConstants.rateUs: StringConstants.rateUs,
          StringConstants.welcome: StringConstants.welcome,
          StringConstants.message: StringConstants.message,
          StringConstants.total: StringConstants.total,
          StringConstants.productsStatus: StringConstants.productsStatus,
          StringConstants.notification: StringConstants.notification,
          StringConstants.upload: StringConstants.upload,
          StringConstants.submit: StringConstants.submit,
          StringConstants.placeAnAdHere: StringConstants.placeAnAdHere,
          StringConstants.search: StringConstants.search,
          StringConstants.cart: StringConstants.cart,
          StringConstants.welcomeToFertileMate:
              StringConstants.welcomeToFertileMate,
          StringConstants.aIDrivenFertilityAnalysis:
              StringConstants.aIDrivenFertilityAnalysis,
          StringConstants.comprehensiveHealthAssessments:
              StringConstants.comprehensiveHealthAssessments,
          StringConstants.boostYourFertilityToday:
              StringConstants.boostYourFertilityToday,
          StringConstants.getStarted: StringConstants.getStarted,
          StringConstants.yourReproductiveHealthJourney:
              StringConstants.yourReproductiveHealthJourney,
          StringConstants.support: StringConstants.support,
          StringConstants.supportText: StringConstants.supportText,
          StringConstants.availableNow: StringConstants.availableNow,
          StringConstants.chatNow: StringConstants.chatNow,
          StringConstants.chat: StringConstants.chat,
          StringConstants.healthAssessment: StringConstants.healthAssessment,
          StringConstants.bloodTests: StringConstants.bloodTests,
          StringConstants.result: StringConstants.result,
          StringConstants.prediabetesAssessment:
              StringConstants.prediabetesAssessment,
          StringConstants.document: StringConstants.document,
          StringConstants.personalInfo: StringConstants.personalInfo,
          StringConstants.yourName: StringConstants.yourName,
          StringConstants.occupation: StringConstants.occupation,
          StringConstants.employer: StringConstants.employer,
          StringConstants.usCitizen: StringConstants.usCitizen,
          StringConstants.contactInfo: StringConstants.contactInfo,
          StringConstants.rotProtection: StringConstants.rotProtection,
          StringConstants.buyWithoutWorries: StringConstants.buyWithoutWorries,
          StringConstants.edit: StringConstants.edit,
          StringConstants.shareYourOpinion: StringConstants.shareYourOpinion,
          StringConstants.yourRatingForThisProductGood:
              StringConstants.yourRatingForThisProductGood,
          StringConstants.typeHere: StringConstants.typeHere,
          StringConstants.send: StringConstants.send,
          StringConstants.categories: StringConstants.categories,
          StringConstants.seeAll: StringConstants.seeAll,
          StringConstants.reportProduct: StringConstants.reportProduct,
          StringConstants.electronics: StringConstants.electronics,
          StringConstants.nearYou: StringConstants.nearYou,
          StringConstants.bestSeller: StringConstants.bestSeller,
          StringConstants.share: StringConstants.share,
          StringConstants.rotAllRightsReserved:
              StringConstants.rotAllRightsReserved,
          StringConstants.changeOfConsent: StringConstants.changeOfConsent,
          StringConstants.privacyPolicies: StringConstants.privacyPolicies,
          StringConstants.termsAndConditions:
              StringConstants.termsAndConditions,
          StringConstants.legalWarning: StringConstants.legalWarning,
          StringConstants.legal: StringConstants.legal,
          StringConstants.coexistenceRules: StringConstants.coexistenceRules,
          StringConstants.securityAdvice: StringConstants.securityAdvice,
          StringConstants.tipsAndRules: StringConstants.tipsAndRules,
          StringConstants.consultationInProgress:
              StringConstants.consultationInProgress,
          StringConstants.helpCenter: StringConstants.helpCenter,
          StringConstants.medium: StringConstants.medium,
          StringConstants.addNewAccount: StringConstants.addNewAccount,
          StringConstants.cars: StringConstants.cars,
          StringConstants.motorcycle: StringConstants.motorcycle,
          StringConstants.realEstate: StringConstants.realEstate,
          StringConstants.employment: StringConstants.employment,
          StringConstants.business: StringConstants.business,
          StringConstants.services: StringConstants.services,
          StringConstants.computer: StringConstants.computer,
          StringConstants.phone: StringConstants.phone,
          StringConstants.baby: StringConstants.baby,
          StringConstants.games: StringConstants.games,
          StringConstants.fashion: StringConstants.fashion,
          StringConstants.sports: StringConstants.sports,
          StringConstants.leisure: StringConstants.leisure,
          StringConstants.agriculture: StringConstants.agriculture,
          StringConstants.community: StringConstants.community,
          StringConstants.training: StringConstants.training,
          StringConstants.imageAndSound: StringConstants.imageAndSound,
          StringConstants.sportsAndNautical: StringConstants.sportsAndNautical,
          StringConstants.computerAndElectronic:
              StringConstants.computerAndElectronic,
          StringConstants.hobbiesAndLeisure: StringConstants.hobbiesAndLeisure,
          StringConstants.engineAndAccessories:
              StringConstants.engineAndAccessories,
          StringConstants.homeAndGarden: StringConstants.homeAndGarden,
          StringConstants.collecting: StringConstants.collecting,
          StringConstants.tourism: StringConstants.tourism,
          StringConstants.description: StringConstants.description,
          StringConstants.title: StringConstants.title,
          StringConstants.category: StringConstants.category,
          StringConstants.productLocation: StringConstants.productLocation,
          StringConstants.city: StringConstants.city,
          StringConstants.country: StringConstants.country,
          StringConstants.zipCode: StringConstants.zipCode,
          StringConstants.brand: StringConstants.brand,
          StringConstants.hashtag: StringConstants.hashtag,
          StringConstants.price: StringConstants.price,
          StringConstants.currency: StringConstants.currency,
          StringConstants.postAdd: StringConstants.postAdd,
          StringConstants.hire: StringConstants.hire,
          StringConstants.rent: StringConstants.rent,
          StringConstants.exchange: StringConstants.exchange,
          StringConstants.buy: StringConstants.buy,
          StringConstants.learnMore: StringConstants.learnMore,
          StringConstants.sell: StringConstants.sell,
          StringConstants.enableShipping: StringConstants.enableShipping,
          StringConstants.keepExploring: StringConstants.keepExploring,
          StringConstants.ongoing: StringConstants.ongoing,
          StringConstants.completed: StringConstants.completed,
          StringConstants.inWind: StringConstants.inWind,
          StringConstants.inProgress: StringConstants.inProgress,
          StringConstants.finished: StringConstants.finished,
          StringConstants.products: StringConstants.products,
          StringConstants.published: StringConstants.published,
          StringConstants.info: StringConstants.info,
          StringConstants.searches: StringConstants.searches,
          StringConstants.friend: StringConstants.friend,
          StringConstants.editPrice: StringConstants.editPrice,
          StringConstants.forSecurity: StringConstants.forSecurity,
          StringConstants.getPaid: StringConstants.getPaid,
          StringConstants.purchasesStatus: StringConstants.purchasesStatus,
          StringConstants.twoStepVerification:
              StringConstants.twoStepVerification,
          StringConstants.useVerificationMethods:
              StringConstants.useVerificationMethods,
          StringConstants.verifyThatThisAccount:
              StringConstants.verifyThatThisAccount,
          StringConstants.chooseHowToReceive:
              StringConstants.chooseHowToReceive,
          StringConstants.appUnlock: StringConstants.appUnlock,
          StringConstants.linkedDevices: StringConstants.linkedDevices,
          StringConstants.collaborator: StringConstants.collaborator,
          StringConstants.unlockingTheApp: StringConstants.unlockingTheApp,
          StringConstants.youUseTouchId: StringConstants.youUseTouchId,
          StringConstants.myProducts: StringConstants.myProducts,
          StringConstants.addNewCard: StringConstants.addNewCard,
          StringConstants.getNotifiedIfAnyOfYourProductsExpire:
              StringConstants.getNotifiedIfAnyOfYourProductsExpire,
          StringConstants.expiredProducts: StringConstants.expiredProducts,
          StringConstants.mySearches: StringConstants.mySearches,
          StringConstants.myFavorites: StringConstants.myFavorites,
          StringConstants.searchAlerts: StringConstants.searchAlerts,
          StringConstants.priceDrop: StringConstants.priceDrop,
          StringConstants.favoritesSold: StringConstants.favoritesSold,
          StringConstants.favoritesReserved: StringConstants.favoritesReserved,
          StringConstants.newProducts: StringConstants.newProducts,
          StringConstants.additionalOptions: StringConstants.additionalOptions,
          StringConstants.tipsTndSuggestions:
              StringConstants.tipsTndSuggestions,
          StringConstants.promotionsAndNewFeatures:
              StringConstants.promotionsAndNewFeatures,
          StringConstants.collaborators: StringConstants.collaborators,
          StringConstants.somethingWentWrong:
              StringConstants.somethingWentWrong,
          StringConstants.weAreWorkingToSolveIt:
              StringConstants.weAreWorkingToSolveIt,
          StringConstants.ifTheProblemPersists:
              StringConstants.ifTheProblemPersists,
          StringConstants.code: StringConstants.code,
          StringConstants.retry: StringConstants.retry,
          StringConstants.useAnotherMethod: StringConstants.useAnotherMethod,
          StringConstants.eliminate: StringConstants.eliminate,
          StringConstants.readyWeSendYour: StringConstants.readyWeSendYour,
          StringConstants.theInvitationIsValidUntilSunday:
              StringConstants.theInvitationIsValidUntilSunday,
          StringConstants.resendInvitation: StringConstants.resendInvitation,
          StringConstants.createAnotherInvitation:
              StringConstants.createAnotherInvitation,
          StringConstants.seeYourCollaborators:
              StringConstants.seeYourCollaborators,
          StringConstants.seeDetails: StringConstants.seeDetails,
          StringConstants.inviteCollaborator:
              StringConstants.inviteCollaborator,
          StringConstants.manageRoles: StringConstants.manageRoles,
          StringConstants.enterTheEmailOfTheCollaborator:
              StringConstants.enterTheEmailOfTheCollaborator,
          StringConstants.keepInMindThatYourEmailMust:
              StringConstants.keepInMindThatYourEmailMust,
          StringConstants.continueText: StringConstants.continueText,
          StringConstants.protectedByReCAPTCHA:
              StringConstants.protectedByReCAPTCHA,
          StringConstants.privacy: StringConstants.privacy,
          StringConstants.chooseARole: StringConstants.chooseARole,
          StringConstants.enterTheVerificationCode:
              StringConstants.enterTheVerificationCode,
          StringConstants.youReceived: StringConstants.youReceived,
          StringConstants.resendCode: StringConstants.resendCode,
          StringConstants.administrator: StringConstants.administrator,
          StringConstants.supervisor: StringConstants.supervisor,
          StringConstants.createNewRole: StringConstants.createNewRole,
          StringConstants.goBack: StringConstants.goBack,
          StringConstants.accounts: StringConstants.accounts,
          StringConstants.recharge: StringConstants.recharge,
          StringConstants.charge: StringConstants.charge,
          StringConstants.sendMoney: StringConstants.sendMoney,
          StringConstants.pay: StringConstants.pay,
          StringConstants.withdraw: StringConstants.withdraw,
          StringConstants.historyOfMovements:
              StringConstants.historyOfMovements,
          StringConstants.bankInformation: StringConstants.bankInformation,
          StringConstants.confirm: StringConstants.confirm,
          StringConstants.editRolePermissions:
              StringConstants.editRolePermissions,
          StringConstants.changeEmail: StringConstants.changeEmail,
          StringConstants.changeRole: StringConstants.changeRole,
          StringConstants.iAcceptThe: StringConstants.iAcceptThe,
          StringConstants.converter: StringConstants.converter,
          StringConstants.forTheUseOfTheCollaboratorsTool:
              StringConstants.forTheUseOfTheCollaboratorsTool,
          StringConstants.cancel: StringConstants.cancel,
          StringConstants.keepInWallet: StringConstants.keepInWallet,
          StringConstants.withdrawBalance: StringConstants.withdrawBalance,
          StringConstants.useTheConverter: StringConstants.useTheConverter,
          StringConstants.conditions: StringConstants.conditions,
          StringConstants.sendInvitation: StringConstants.sendInvitation,
          StringConstants.rotPro: StringConstants.rotPro,
          StringConstants.addNew: StringConstants.addNew,
          StringConstants.departures: StringConstants.departures,
          StringConstants.appetizer: StringConstants.appetizer,
          StringConstants.all: StringConstants.all,
          StringConstants.local: StringConstants.local,
          StringConstants.swift: StringConstants.swift,
          StringConstants.bicSwiftCode: StringConstants.bicSwiftCode,
          StringConstants.bankNameAndAddress:
              StringConstants.bankNameAndAddress,
          StringConstants.recipient: StringConstants.recipient,
          StringConstants.useThisData: StringConstants.useThisData,
          StringConstants.provideThisData: StringConstants.provideThisData,
          StringConstants.ifTheIssuingBank: StringConstants.ifTheIssuingBank,
          StringConstants.ifYourEmployer: StringConstants.ifYourEmployer,
          StringConstants.documents: StringConstants.documents,
          StringConstants.bankStatement: StringConstants.bankStatement,
          StringConstants.accountConfirmation:
              StringConstants.accountConfirmation,
          StringConstants.onlyForInternationalTransfers:
              StringConstants.onlyForInternationalTransfers,
          StringConstants.were: StringConstants.were,
          StringConstants.onlyForLocalTransfers:
              StringConstants.onlyForLocalTransfers,
          StringConstants.currencyAccount: StringConstants.currencyAccount,
          StringConstants.flexibleAccount: StringConstants.flexibleAccount,
          StringConstants.pockets: StringConstants.pockets,
          StringConstants.saveMoneyAndManage:
              StringConstants.saveMoneyAndManage,
          StringConstants.jointAccount: StringConstants.jointAccount,
          StringConstants.anAccountForAllTypes:
              StringConstants.anAccountForAllTypes,
          StringConstants.getUpTo: StringConstants.getUpTo,
          StringConstants.proAccount: StringConstants.proAccount,
          StringConstants.howMuchMoneyDoYouWantToRecharge:
              StringConstants.howMuchMoneyDoYouWantToRecharge,
          StringConstants.rateAccordingToTheAmountOfTheRecharge:
              StringConstants.rateAccordingToTheAmountOfTheRecharge,
          StringConstants.reloadWallet: StringConstants.reloadWallet,
          StringConstants.transferToBank: StringConstants.transferToBank,
          StringConstants.howMuchMoney: StringConstants.howMuchMoney,
          StringConstants.rechargeSummary: StringConstants.rechargeSummary,
          StringConstants.rechargeFee: StringConstants.rechargeFee,
          StringConstants.rechargeCarriedOut:
              StringConstants.rechargeCarriedOut,
          StringConstants.goToWallet: StringConstants.goToWallet,
          StringConstants.theMoneyIsAlready: StringConstants.theMoneyIsAlready,
          StringConstants.aReadyToUse: StringConstants.aReadyToUse,
          StringConstants.credit: StringConstants.credit,
          StringConstants.discoverLoansAndCreditCards:
              StringConstants.discoverLoansAndCreditCards,
          StringConstants.accountGreaterThanEighteen:
              StringConstants.accountGreaterThanEighteen,
          StringConstants.linkedAccount: StringConstants.linkedAccount,
          StringConstants.checkAllYourBankAccountsInOnePlace:
              StringConstants.checkAllYourBankAccountsInOnePlace,
          StringConstants.accountsForChildren:
              StringConstants.accountsForChildren,
          StringConstants.moreThanThirtyCurrencies:
              StringConstants.moreThanThirtyCurrencies,
          StringConstants.itOffersYouSolutions:
              StringConstants.itOffersYouSolutions,
          StringConstants.findTheBestSubscription:
              StringConstants.findTheBestSubscription,
          StringConstants.searchForCollaborator:
              StringConstants.searchForCollaborator,
          StringConstants.getNotifiedWhenNewProductsFit:
              StringConstants.getNotifiedWhenNewProductsFit,
          StringConstants.getNotifiedAboutAnyNewsRegarding:
              StringConstants.getNotifiedAboutAnyNewsRegarding,
          StringConstants.getNotifiedAboutPromotionsAndOther:
              StringConstants.getNotifiedAboutPromotionsAndOther,
        },
      };
}
