name: rot_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.2.0
  pin_code_fields: ^8.0.1
  google_nav_bar: ^5.0.6
  country_code_picker: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  in_app_update: ^4.2.2
  google_maps_flutter: ^2.5.0
  http: ^1.2.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/image_logo.png"
  android:
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/images/image_logo.png"
    round_icon: true
  ios:
    image_path: "assets/images/image_logo.png"
    is_rounded: true
    precomposed: true



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/un_used_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
